services:
  - type: web
    name: quantum-scraper-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: ALLOWED_ORIGINS
        value: https://quantum-scraper-beryl.vercel.app
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
